import { useCallback } from 'react';
import { useFocusEffect, router } from 'expo-router';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { FileCheck2, RefreshCw, ShieldCheck } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useReceipts } from '@/hooks/useMarkets';
import { colors, font, radius, spacing } from '@/theme';
import type { ExecutionReceipt } from '@/types/market';
import { formatCompactUsd, formatPrice } from '@/utils/format';

export default function ReceiptsScreen() {
  const { data: receipts, loading, error, retry } = useReceipts();
  useFocusEffect(useCallback(() => { void retry(); }, [retry]));

  return <SafeAreaView edges={['top']} style={styles.safe}><FlatList contentContainerStyle={styles.content} data={loading || error ? [] : receipts} keyExtractor={(item) => item.id} ListHeaderComponent={<View style={styles.header}><Text style={styles.eyebrow}>PERSONAL EXECUTION DATA</Text><Text style={styles.title}>Analysis receipts</Text><Text style={styles.copy}>Build a record of the prices, liquidity and routes you evaluated before each trade.</Text><View style={styles.notice}><ShieldCheck color={colors.amber} size={17} /><Text style={styles.noticeText}>Saved checks are unverified until an on-chain transaction is attached.</Text></View></View>} ItemSeparatorComponent={() => <View style={{ height: spacing.md }} />} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardTop}><View style={styles.symbol}><Text style={styles.symbolText}>{item.symbol.slice(0, 1)}</Text></View><View style={styles.identity}><Text style={styles.pair}>{item.side === 'buy' ? 'Buy' : 'Sell'} {item.symbol}</Text><Text style={styles.date}>{new Date(item.createdAt).toLocaleString()}</Text></View><View style={styles.status}><Text style={styles.statusText}>ANALYSIS</Text></View></View><View style={styles.metrics}><ReceiptMetric label="Order" value={formatCompactUsd(item.requestedUsd)} /><ReceiptMetric label="Expected fill" value={formatPrice(item.expectedAveragePrice)} /><ReceiptMetric label="Impact" value={`${item.expectedImpactBps.toFixed(1)} bps`} /><ReceiptMetric label="Score" value={`${item.qualityScore}/100`} /></View><View style={styles.cardFoot}><Text style={styles.bestVenue}>Best venue: {item.bestVenue}</Text><Text style={styles.id}>{item.id}</Text></View></View>} ListEmptyComponent={loading ? <View style={styles.state}><ActivityIndicator color={colors.amber} /><Text style={styles.stateTitle}>Loading receipts</Text></View> : error ? <View style={styles.state}><RefreshCw color={colors.red} size={24} /><Text style={styles.stateTitle}>Couldn’t load receipts</Text><Text style={styles.stateCopy}>{error}</Text><Pressable accessibilityRole="button" onPress={() => void retry()} style={styles.action}><Text style={styles.actionText}>Try again</Text></Pressable></View> : <View style={styles.state}><FileCheck2 color={colors.amber} size={28} /><Text style={styles.stateTitle}>No analysis receipts yet</Text><Text style={styles.stateCopy}>Open a tokenized-stock market, analyze an order, then save the result here.</Text><Pressable accessibilityRole="button" onPress={() => router.push('/market/aaplx-usdc')} style={styles.action}><Text style={styles.actionText}>Analyze AAPLX</Text></Pressable></View>} /></SafeAreaView>;
}

function ReceiptMetric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }

const styles = StyleSheet.create({
  safe: { backgroundColor: colors.canvas, flex: 1 }, content: { padding: spacing.lg, paddingBottom: spacing.xxl }, header: { paddingBottom: spacing.xl }, eyebrow: { color: colors.amber, fontFamily: font.monoMedium, fontSize: 10, letterSpacing: 1.1 }, title: { color: colors.text, fontFamily: font.sansSemiBold, fontSize: 30, letterSpacing: -0.8, marginTop: spacing.sm }, copy: { color: colors.textMuted, fontFamily: font.sans, fontSize: 13, lineHeight: 20, marginTop: spacing.sm, maxWidth: 360 }, notice: { alignItems: 'center', backgroundColor: colors.amberSoft, borderRadius: radius.md, flexDirection: 'row', gap: spacing.sm, marginTop: spacing.lg, padding: spacing.md }, noticeText: { color: colors.textMuted, flex: 1, fontFamily: font.sans, fontSize: 11, lineHeight: 17 },
  card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, padding: spacing.lg }, cardTop: { alignItems: 'center', flexDirection: 'row' }, symbol: { alignItems: 'center', backgroundColor: colors.amberSoft, borderRadius: radius.md, height: 42, justifyContent: 'center', width: 42 }, symbolText: { color: colors.amber, fontFamily: font.sansSemiBold, fontSize: 16 }, identity: { flex: 1, marginLeft: spacing.md }, pair: { color: colors.text, fontFamily: font.sansSemiBold, fontSize: 14 }, date: { color: colors.textSubtle, fontFamily: font.mono, fontSize: 9, marginTop: 3 }, status: { backgroundColor: colors.elevated, borderRadius: radius.pill, paddingHorizontal: 8, paddingVertical: 5 }, statusText: { color: colors.textMuted, fontFamily: font.monoMedium, fontSize: 8, letterSpacing: 0.5 }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.lg }, metric: { backgroundColor: colors.canvas, borderRadius: radius.sm, minWidth: '47%', padding: spacing.md }, metricLabel: { color: colors.textSubtle, fontFamily: font.sans, fontSize: 10 }, metricValue: { color: colors.text, fontFamily: font.monoMedium, fontSize: 13, fontVariant: ['tabular-nums'], marginTop: 3 }, cardFoot: { borderTopColor: colors.border, borderTopWidth: 1, marginTop: spacing.md, paddingTop: spacing.md }, bestVenue: { color: colors.green, fontFamily: font.sansMedium, fontSize: 11 }, id: { color: colors.textSubtle, fontFamily: font.mono, fontSize: 8, marginTop: 4 },
  state: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, gap: spacing.sm, padding: spacing.xxl }, stateTitle: { color: colors.text, fontFamily: font.sansSemiBold, fontSize: 15 }, stateCopy: { color: colors.textMuted, fontFamily: font.sans, fontSize: 12, lineHeight: 18, maxWidth: 280, textAlign: 'center' }, action: { alignItems: 'center', backgroundColor: colors.amber, borderRadius: radius.md, justifyContent: 'center', marginTop: spacing.sm, minHeight: 44, paddingHorizontal: spacing.lg }, actionText: { color: colors.canvas, fontFamily: font.sansSemiBold, fontSize: 12 },
});
